baseurl = "https://nextcloudbox.netlify.app/"
disableLanguages = []
googleAnalytics = ""
summarylength = "20"
theme = "vex-hugo"
title = "Nextcloudbox"
[Languages.en]
contentDir = "content/english"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
languageCode = "en-us"
languageName = "En"
weight = "2"
[Languages.fr]
contentDir = "content/french"
copyright = "Crée par [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
languageCode = "fr-fr"
languageName = "Fr"
weight = "1"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Politique de confidentialité"
url = "privacy-policy"
weight = 3
[[menu.footer]]
name = "Conditions d'utilisation"
url = "terms-conditions"
weight = 2
[[menu.footer]]
name = "Contact"
url = "contact"
weight = 1
[[menu.main]]
name = "Contactez-nous"
url = "contact"
weight = 4
[[menu.main]]
name = "Avis"
pre = "#"
url = "testimonial"
weight = 3
[[menu.main]]
name = "Produits"
url = "products"
weight = 2
[[menu.main]]
name = "Accueil"
url = "/"
weight = 1
[params]
author = "Themefisher"
contact_form_action = "#"
currency = "€"
description = "Nextcloudbox, Vous êtes uniques, vos données personnelles le sont aussi, elles doivent le rester. Votre Cloud maison, un seul disque dur pour toutes vos données. Votre espace de stockage accessible de partout."
logo = "images/logo.png"
logo_width = "100px"
snipcart_api = "ODdhNDc3ZmEtMDYzOS00NTA2LThmNDEtNmVmZTQwYzliNmQ5NjM3NDY1OTgyNjk4NzkyODkw"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"
[params.preloader]
enable = true
preloader = ""
[params.subscription]
mailchimp_form_action = "https://protonmail.us7.list-manage.com/subscribe/post?u=4ea9c84ef3ea7de79bad5b066&amp;id=dde3f07ec7"
mailchimp_form_name = "b_4ea9c84ef3ea7de79bad5b066_dde3f07ec7"
